In [1]:
import numpy as np
import pickle

In [3]:
with open('train_qa.txt', 'rb') as f:
    train_data = pickle.load(f)

In [7]:
with open('test_qa.txt', 'rb') as f:
    test_data = pickle.load(f)

In [8]:
' '.join(train_data[0][0])

'Mary got the milk there . John moved to the bedroom .'

In [11]:
whole_data =  train_data + test_data

In [12]:
len(whole_data)

2000

In [15]:
vocab = set()

for story,question,answer in whole_data:
    vocab = vocab.union(set(story))
    vocab = vocab.union(set(question))
vocab.add('no')
vocab.add('yes')

In [17]:
vocab_len = len(vocab)+1

In [18]:
vocab_len

38

In [19]:
all_story_len = [len(data[0]) for data in whole_data]

In [20]:
# length of all stories
all_story_len

[12,
 23,
 35,
 47,
 59,
 13,
 26,
 37,
 50,
 62,
 12,
 24,
 37,
 49,
 60,
 12,
 25,
 38,
 50,
 62,
 12,
 24,
 36,
 47,
 59,
 12,
 25,
 36,
 48,
 59,
 12,
 26,
 39,
 51,
 63,
 13,
 24,
 37,
 50,
 62,
 13,
 26,
 38,
 50,
 63,
 13,
 25,
 36,
 49,
 61,
 13,
 26,
 39,
 51,
 64,
 13,
 25,
 37,
 50,
 62,
 13,
 25,
 37,
 50,
 61,
 12,
 25,
 38,
 50,
 62,
 12,
 25,
 37,
 50,
 61,
 12,
 25,
 36,
 48,
 60,
 12,
 24,
 36,
 48,
 60,
 13,
 25,
 37,
 49,
 60,
 13,
 25,
 39,
 51,
 64,
 12,
 25,
 37,
 49,
 61,
 12,
 25,
 38,
 50,
 61,
 12,
 24,
 36,
 49,
 62,
 13,
 25,
 37,
 50,
 62,
 12,
 23,
 35,
 47,
 59,
 12,
 25,
 37,
 48,
 73,
 12,
 24,
 37,
 49,
 61,
 12,
 24,
 37,
 49,
 62,
 14,
 26,
 37,
 49,
 62,
 12,
 23,
 35,
 48,
 59,
 12,
 24,
 36,
 49,
 61,
 13,
 25,
 37,
 49,
 61,
 12,
 25,
 37,
 50,
 62,
 12,
 24,
 36,
 47,
 58,
 12,
 24,
 36,
 48,
 61,
 25,
 38,
 50,
 62,
 74,
 13,
 25,
 37,
 49,
 62,
 12,
 24,
 37,
 49,
 62,
 12,
 24,
 36,
 48,
 60,
 12,
 24,
 36,
 48,
 61,
 12,
 25,
 36,
 50,
 62,


In [33]:
# length of the longest story 
max_story_len = max(all_story_len)

In [22]:
all_question_len = [len(data[0]) for data in whole_data]
max_question_len = max(all_question_len)

In [24]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import Tokenizer

In [26]:
tokenizer = Tokenizer(filters=[])
tokenizer.fit_on_texts(vocab)

In [27]:
tokenizer.word_index

{'took': 1,
 'the': 2,
 'in': 3,
 'bedroom': 4,
 'bathroom': 5,
 'to': 6,
 'left': 7,
 'discarded': 8,
 'travelled': 9,
 'john': 10,
 'moved': 11,
 'garden': 12,
 'went': 13,
 'picked': 14,
 'dropped': 15,
 'apple': 16,
 'office': 17,
 'daniel': 18,
 'hallway': 19,
 'back': 20,
 'grabbed': 21,
 '.': 22,
 'milk': 23,
 'no': 24,
 'got': 25,
 'yes': 26,
 'put': 27,
 'is': 28,
 'up': 29,
 '?': 30,
 'down': 31,
 'football': 32,
 'mary': 33,
 'journeyed': 34,
 'there': 35,
 'kitchen': 36,
 'sandra': 37}

In [28]:
train_story_text = []
train_question_text= []
train_answers =[]

In [29]:
for story, question, answer in train_data:
    train_story_text.append(story)
    train_question_text.append(question)
    train_answers.append(answer)

In [30]:
train_story_seq = tokenizer.texts_to_sequences(train_story_text)

In [31]:
len(train_story_seq)

1000

In [34]:
def vector_stories(data,word_index= tokenizer.word_index,max_story_len= max_story_len,max_question_len=max_question_len):
    X =[]
    Xq =[]
    Y=[]
    for story,query,answer in data:
        x = [word_index[word.lower()] for word in story]
        xq = [word_index[word.lower()] for word in query]
        y = np.zeros(len(word_index)+1)
        y[word_index[answer]]=1
        X.append(x)
        Xq.append(xq)
        Y.append(y)
    return (pad_sequences(X,maxlen= max_story_len),pad_sequences(Xq,maxlen= max_question_len),np.array(Y))

In [35]:
inputs_train, query_train, answer_train = vector_stories(train_data)

In [36]:
inputs_test, query_test, answer_test = vector_stories(test_data)

In [37]:
tokenizer.word_index['yes']

26

In [38]:
tokenizer.word_index

{'took': 1,
 'the': 2,
 'in': 3,
 'bedroom': 4,
 'bathroom': 5,
 'to': 6,
 'left': 7,
 'discarded': 8,
 'travelled': 9,
 'john': 10,
 'moved': 11,
 'garden': 12,
 'went': 13,
 'picked': 14,
 'dropped': 15,
 'apple': 16,
 'office': 17,
 'daniel': 18,
 'hallway': 19,
 'back': 20,
 'grabbed': 21,
 '.': 22,
 'milk': 23,
 'no': 24,
 'got': 25,
 'yes': 26,
 'put': 27,
 'is': 28,
 'up': 29,
 '?': 30,
 'down': 31,
 'football': 32,
 'mary': 33,
 'journeyed': 34,
 'there': 35,
 'kitchen': 36,
 'sandra': 37}

In [43]:
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Input, Activation,Dense,Permute,Dropout,add,dot,concatenate,LSTM,Embedding

In [57]:
vocab_size = len(vocab)+1

In [58]:
input_sequence= Input((max_story_len,))
question = Input((max_question_len,))
vocab_size = len(vocab)+1
input_encoder_m = Sequential()
input_encoder_m.add(Embedding(input_dim= vocab_size,output_dim=64))
# 30% of neurons are dropped while training
input_encoder_m.add(Dropout(0.3))
# samples,story_max_len,embedding_dim

In [59]:
input_encoder_c = Sequential()
input_encoder_c.add(Embedding(input_dim= vocab_size,output_dim=max_question_len))
# 30% of neurons are dropped while training
input_encoder_c.add(Dropout(0.3))
# samples,story_max_len,max_question_len

In [60]:
question_encoder = Sequential()
question_encoder.add(Embedding(input_dim= vocab_size,output_dim=64,input_length=max_question_len))
# 30% of neurons are dropped while training
question_encoder.add(Dropout(0.3))
# samples,story_max_len,embedding_dim

In [61]:
input_encoded_m = input_encoder_m(input_sequence)
input_encoded_c = input_encoder_c(input_sequence)
question_encoded = question_encoder(question)

In [62]:
match = dot([input_encoded_m,question_encoded],axes=(2,2))
match = Activation('softmax')(match)
response = add([match,input_encoded_c])
response = Permute((2,1))(response)
answer = concatenate([response,question_encoded])
answer

<KerasTensor: shape=(None, 86, 150) dtype=float32 (created by layer 'concatenate_3')>

In [63]:
answer = LSTM(32)(answer)
answer = Dropout(0.5)(answer)
answer = Dense(vocab_size)(answer)
answer = Activation('softmax')(answer)
model = Model([input_sequence,question],answer)
model.compile(optimizer ='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])

In [65]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_5 (InputLayer)           [(None, 86)]         0           []                               
                                                                                                  
 input_6 (InputLayer)           [(None, 86)]         0           []                               
                                                                                                  
 sequential_4 (Sequential)      (None, None, 64)     2432        ['input_5[0][0]']                
                                                                                                  
 sequential_6 (Sequential)      (None, 86, 64)       2432        ['input_6[0][0]']                
                                                                                              

In [70]:
history = model.fit([inputs_train,query_train],answer_train,batch_size=32,epochs=100,validation_data=([inputs_train,query_train],answer_train))

Epoch 1/100
32/32 [==============================] - 2s 71ms/step - loss: 0.2990 - accuracy: 0.8640 - val_loss: 0.2854 - val_accuracy: 0.8670
Epoch 2/100
32/32 [==============================] - 1s 43ms/step - loss: 0.2907 - accuracy: 0.8780 - val_loss: 0.2791 - val_accuracy: 0.8700
Epoch 3/100
32/32 [==============================] - 2s 50ms/step - loss: 0.2963 - accuracy: 0.8550 - val_loss: 0.2030 - val_accuracy: 0.9110
Epoch 4/100
32/32 [==============================] - 1s 44ms/step - loss: 0.2936 - accuracy: 0.8650 - val_loss: 0.2465 - val_accuracy: 0.8670
Epoch 5/100
32/32 [==============================] - 1s 44ms/step - loss: 0.2564 - accuracy: 0.8830 - val_loss: 0.1984 - val_accuracy: 0.9070
Epoch 6/100
32/32 [==============================] - 2s 51ms/step - loss: 0.3100 - accuracy: 0.8570 - val_loss: 0.2063 - val_accuracy: 0.9000
Epoch 7/100
32/32 [==============================] - 1s 42ms/step - loss: 0.2827 - accuracy: 0.8620 - val_loss: 0.1855 - val_accuracy: 0.9180
Epoch 

32/32 [==============================] - 2s 48ms/step - loss: 0.1520 - accuracy: 0.9390 - val_loss: 0.0675 - val_accuracy: 0.9750
Epoch 59/100
32/32 [==============================] - 2s 50ms/step - loss: 0.1446 - accuracy: 0.9360 - val_loss: 0.0973 - val_accuracy: 0.9510
Epoch 60/100
32/32 [==============================] - 1s 45ms/step - loss: 0.1413 - accuracy: 0.9520 - val_loss: 0.0906 - val_accuracy: 0.9600
Epoch 61/100
32/32 [==============================] - 1s 47ms/step - loss: 0.1577 - accuracy: 0.9410 - val_loss: 0.0909 - val_accuracy: 0.9640
Epoch 62/100
32/32 [==============================] - 2s 53ms/step - loss: 0.1522 - accuracy: 0.9350 - val_loss: 0.0723 - val_accuracy: 0.9730
Epoch 63/100
32/32 [==============================] - 1s 45ms/step - loss: 0.1356 - accuracy: 0.9490 - val_loss: 0.0857 - val_accuracy: 0.9610
Epoch 64/100
32/32 [==============================] - 1s 41ms/step - loss: 0.1517 - accuracy: 0.9410 - val_loss: 0.2193 - val_accuracy: 0.9360
Epoch 65/100

In [72]:
model.save('my_chatbot.h5')
model.load_weights('my_chatbot.h5')

/Users/isita/Downloads/anaconda3/lib/python3.8/site-packages/keras/engine/functional.py:1410: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  layer_config = serialize_layer_fn(layer)


In [75]:
pred_results = model.predict(([inputs_test,query_test]))

In [76]:
pred_results[0]

array([1.6935620e-13, 1.3406125e-13, 1.8088013e-13, 1.3913018e-13,
       1.3542904e-13, 1.7183101e-13, 1.7514122e-13, 1.8193268e-13,
       1.6109980e-13, 1.5104281e-13, 1.4737347e-13, 1.5203072e-13,
       1.5363105e-13, 1.9439390e-13, 1.8451523e-13, 1.3260660e-13,
       1.2069087e-13, 2.0295359e-13, 1.3278477e-13, 1.4106693e-13,
       1.5198665e-13, 1.6825378e-13, 1.3300885e-13, 1.2696490e-13,
       9.9538773e-01, 1.6235589e-13, 4.6122619e-03, 1.8926883e-13,
       1.2463082e-13, 1.4168120e-13, 1.1927339e-13, 1.6716108e-13,
       1.5452857e-13, 1.4337370e-13, 1.2092405e-13, 1.2918933e-13,
       1.9927881e-13, 1.3922468e-13], dtype=float32)

In [77]:
np.argmax(pred_results[0])

24

In [80]:
for key,value in tokenizer.word_index.items():
    if value==np.argmax(pred_results[0]):
        k =key

In [81]:
k

'no'

In [83]:
pred_results[0][24]

0.99538773

In [101]:
story = 'John left the football in the kitchen'
question ='Is the football in the kitchen ?'
answer = 'yes'

In [102]:
my_data = [(story.split(),question.split(),'yes')]

In [103]:
my_data

[(['John', 'left', 'the', 'football', 'in', 'the', 'kitchen'],
  ['Is', 'the', 'football', 'in', 'the', 'kitchen', '?'],
  'yes')]

In [104]:
my_story, my_ques, my_ans = vector_stories(my_data)

In [105]:
my_ques

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 28,
         2, 32,  3,  2, 36, 30]], dtype=int32)

In [106]:
my_ans

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.]])

In [107]:
result = model.predict(([my_story,my_ques]))

In [108]:
val_max = np.argmax(result[0])

In [110]:
for key,value in tokenizer.word_index.items():
    if value == val_max:
        k = key

In [111]:
k

'yes'

In [113]:
result[0][val_max]

0.7602364